apiVersion: v1
kind: ServiceAccount
metadata:
  name: pubsub-push-config-controller
---
apiVersion: v1
kind: Secret
metadata:
  name: pubsub-push-config-controller
  annotations:
    kubernetes.io/service-account.name: pubsub-push-config-controller
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsub-push-config-controller
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pubsub-push-config-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pubsub-push-config-controller
subjects:
  - kind: ServiceAccount
    name: pubsub-push-config-controller
    namespace: {{ .Release.Namespace }}
