name: Chart Releaser

on:
  push:
    branches:
      - main
    paths:
      - "chart/Chart.yaml"

jobs:
  trigger-workflow:
    name: Trigger Chart Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: kerwood
          repo: helm-charts
          github_token: ${{ secrets.WORKFLOW_PAT }}
          workflow_file_name: chart-releaser.yaml
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
